package org.bugkillers.core.domain;

import java.util.Date;

public class CommentDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.comment_text
     *
     * @mbggenerated
     */
    private String commentText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.bk_create
     *
     * @mbggenerated
     */
    private Date bkCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.bk_modified
     *
     * @mbggenerated
     */
    private Date bkModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_comment.dr
     *
     * @mbggenerated
     */
    private Byte dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_comment
     *
     * @mbggenerated
     */
    public CommentDO(Integer id, Integer questionId, Integer userId, String commentText, Date createTime, Date updateTime, Date bkCreate, Date bkModified, Byte dr) {
        this.id = id;
        this.questionId = questionId;
        this.userId = userId;
        this.commentText = commentText;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.bkCreate = bkCreate;
        this.bkModified = bkModified;
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.id
     *
     * @return the value of bk_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.question_id
     *
     * @return the value of bk_comment.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.user_id
     *
     * @return the value of bk_comment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.comment_text
     *
     * @return the value of bk_comment.comment_text
     *
     * @mbggenerated
     */
    public String getCommentText() {
        return commentText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.create_time
     *
     * @return the value of bk_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.update_time
     *
     * @return the value of bk_comment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.bk_create
     *
     * @return the value of bk_comment.bk_create
     *
     * @mbggenerated
     */
    public Date getBkCreate() {
        return bkCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.bk_modified
     *
     * @return the value of bk_comment.bk_modified
     *
     * @mbggenerated
     */
    public Date getBkModified() {
        return bkModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_comment.dr
     *
     * @return the value of bk_comment.dr
     *
     * @mbggenerated
     */
    public Byte getDr() {
        return dr;
    }
}