package org.bugkillers.core.domain;

import java.util.Date;

public class QuestionDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.tag_id
     *
     * @mbggenerated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.question_text
     *
     * @mbggenerated
     */
    private String questionText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.bk_create
     *
     * @mbggenerated
     */
    private Date bkCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.bk_modified
     *
     * @mbggenerated
     */
    private Date bkModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_question.dr
     *
     * @mbggenerated
     */
    private Byte dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_question
     *
     * @mbggenerated
     */
    public QuestionDO(Integer id, Integer tagId, Integer userId, String questionText, Date createTime, Date updateTime, Date bkCreate, Date bkModified, Byte dr) {
        this.id = id;
        this.tagId = tagId;
        this.userId = userId;
        this.questionText = questionText;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.bkCreate = bkCreate;
        this.bkModified = bkModified;
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.id
     *
     * @return the value of bk_question.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.tag_id
     *
     * @return the value of bk_question.tag_id
     *
     * @mbggenerated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.user_id
     *
     * @return the value of bk_question.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.question_text
     *
     * @return the value of bk_question.question_text
     *
     * @mbggenerated
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.create_time
     *
     * @return the value of bk_question.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.update_time
     *
     * @return the value of bk_question.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.bk_create
     *
     * @return the value of bk_question.bk_create
     *
     * @mbggenerated
     */
    public Date getBkCreate() {
        return bkCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.bk_modified
     *
     * @return the value of bk_question.bk_modified
     *
     * @mbggenerated
     */
    public Date getBkModified() {
        return bkModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_question.dr
     *
     * @return the value of bk_question.dr
     *
     * @mbggenerated
     */
    public Byte getDr() {
        return dr;
    }
}