package org.bugkillers.core.domain;

import java.util.Date;

public class TagDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_tag.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_tag.bk_create
     *
     * @mbggenerated
     */
    private Date bkCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_tag.bk_modified
     *
     * @mbggenerated
     */
    private Date bkModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_tag.dr
     *
     * @mbggenerated
     */
    private Byte dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    public TagDO(Integer id, String tagName, Date bkCreate, Date bkModified, Byte dr) {
        this.id = id;
        this.tagName = tagName;
        this.bkCreate = bkCreate;
        this.bkModified = bkModified;
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_tag.id
     *
     * @return the value of bk_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_tag.tag_name
     *
     * @return the value of bk_tag.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_tag.bk_create
     *
     * @return the value of bk_tag.bk_create
     *
     * @mbggenerated
     */
    public Date getBkCreate() {
        return bkCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_tag.bk_modified
     *
     * @return the value of bk_tag.bk_modified
     *
     * @mbggenerated
     */
    public Date getBkModified() {
        return bkModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_tag.dr
     *
     * @return the value of bk_tag.dr
     *
     * @mbggenerated
     */
    public Byte getDr() {
        return dr;
    }
}