package org.bugkillers.core.domain;

import java.util.Date;

public class UserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.id
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.user_name
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.nick_name
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.password
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.email
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.head_pic
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.regist_time
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.login_time
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.bk_create
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private Date bkCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.bk_modified
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private Date bkModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_user.dr
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    private Byte dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_user
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public UserDO(Integer id, String userName, String nickName, String password, String email, String headPic, Date registTime, Date loginTime, Date bkCreate, Date bkModified, Byte dr) {
        this.id = id;
        this.userName = userName;
        this.nickName = nickName;
        this.password = password;
        this.email = email;
        this.headPic = headPic;
        this.registTime = registTime;
        this.loginTime = loginTime;
        this.bkCreate = bkCreate;
        this.bkModified = bkModified;
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.id
     *
     * @return the value of bk_user.id
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.user_name
     *
     * @return the value of bk_user.user_name
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.nick_name
     *
     * @return the value of bk_user.nick_name
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.password
     *
     * @return the value of bk_user.password
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.email
     *
     * @return the value of bk_user.email
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.head_pic
     *
     * @return the value of bk_user.head_pic
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.regist_time
     *
     * @return the value of bk_user.regist_time
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.login_time
     *
     * @return the value of bk_user.login_time
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.bk_create
     *
     * @return the value of bk_user.bk_create
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public Date getBkCreate() {
        return bkCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.bk_modified
     *
     * @return the value of bk_user.bk_modified
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public Date getBkModified() {
        return bkModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_user.dr
     *
     * @return the value of bk_user.dr
     *
     * @mbggenerated Mon Jun 08 20:50:03 CST 2015
     */
    public Byte getDr() {
        return dr;
    }
}