package org.bugkillers.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.bugkillers.core.domain.TagDO;
import org.bugkillers.core.domain.TagDOExample;

public interface TagDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    int countByExample(TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    int deleteByExample(TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bk_tag",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bk_tag (id, tag_name, ",
        "bk_create, bk_modified, ",
        "dr)",
        "values (#{id,jdbcType=INTEGER}, #{tagName,jdbcType=VARCHAR}, ",
        "#{bkCreate,jdbcType=TIMESTAMP}, #{bkModified,jdbcType=TIMESTAMP}, ",
        "#{dr,jdbcType=TINYINT})"
    })
    int insert(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    int insertSelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    List<TagDO> selectByExample(TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, tag_name, bk_create, bk_modified, dr",
        "from bk_tag",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TagDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TagDO record, @Param("example") TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TagDO record, @Param("example") TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_tag
     *
     * @mbggenerated
     */
    @Update({
        "update bk_tag",
        "set tag_name = #{tagName,jdbcType=VARCHAR},",
          "bk_create = #{bkCreate,jdbcType=TIMESTAMP},",
          "bk_modified = #{bkModified,jdbcType=TIMESTAMP},",
          "dr = #{dr,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TagDO record);
}